### ISSUE TITLE
Please allow Fraction(0,0)

### ISSUE THREAD

**Issue by jbrucker** [Winternight9/unittesting-Winternight9#1]
Glad to see you have done work on the assignment.

Please allow Fraction(0,0) as a valid fraction.
Since we allow Fraction(1,0) and Fraction(-1,0)
we should also allow Fraction(0,0).
They are all considered "extended numbers".

You don't need to worry about extended numbers,
but consider this:
```python
f = Fraction(1, 0)
g = Fraction(-1, 0)
x = f + g
```
Then `x` is 0/0 (NaN).  So, 0/0 should be allowed if 1/0
is allowed.  Its better than throwing a ValueError.

You can throw ValueError if someone calls Fraction(a,b)
with a or b not an int.

**Comment by Winternight9** [comment]
Already fix that problem.  Thank you for advice.

**Comment by magmagcup** [comment]
"You can throw ValueError if someone calls Fraction(a,b) with a or b not an int."
In my opinion, I think that TypeError might be more suitable in the case when a or b not an int.

**Comment by jbrucker** [comment]
Sirawich is right -- TypeError is better for an incorrect param type.
Thanks for pointing it out.
